### ISSUE TITLE
FYI: Changes to the startup notebook for it to run on colab

### ISSUE THREAD

**Issue by jayurbain** [CompVis/taming-transformers#121]
FYI: Changes to the startup notebook (taming-transformers.ipynb) for it to run on colab:
!pip install einops
!pip install transformers
-> restarted kernel

-- assert c_code.shape[2]*c_code.shape[3] == c_indices.shape[1]
assert c_code.shape[2]*c_code.shape[3] == c_indices.shape[0]

Thanks for your great work!
Jay

**Comment by rromb** [comment]
Hi @jayurbain, thanks for catching this (and sorry it took so long)! Should be fixed with 24268930bf1dce879235a7fddd0b2355b84d7ea6. Btw, while I ran the notebook the model rendered this very nice sample :100: 

![landscape_sample](https://user-images.githubusercontent.com/38811725/149383037-e137ffe4-e887-4328-a5e5-d23c71564c03.png)

**Comment by jayurbain** [comment]
Beautiful!
